### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by aniagarwal97** [philnash/react-programmable-chat#1]
At localhost:3001 it says that **Cannot GET /**

Any solutions?

**Comment by philnash** [comment]
You should open http://localhost:3000/ as that is where the client application is. localhost:3001 is the server and only has a [POST endpoint for generating access tokens](https://github.com/philnash/react-programmable-chat/blob/master/index.js#L12).

**Comment by philnash** [comment]
I'm going to close this issue as I am guessing it's solved. Let me know if you are still having problems.
