### ISSUE TITLE
No work!

### ISSUE THREAD

**Issue by JodieHag** [philnash/react-programmable-chat#2]
Hi!

In localhost:3000 I can't see nothing, no work. 

cp .env.example .env
npm install
npm start

run localhost:3000 ----> ERR_CONNECTION_REFUSED

:S

**Comment by philnash** [comment]
Have you set up all the environment variables from your Twilio account that you need? See [this section in the README](https://github.com/philnash/react-programmable-chat#setting-up-the-app).

Is there an error message in the terminal at all?

**Comment by JodieHag** [comment]
oh! I managed to make it work. I just had to enter the client folder and do npm install, to also run the react app.

Your work has helped me a lot, thank you very much for the contribution! :)

**Comment by philnash** [comment]
Ah, ok. I should probably update the README to make sure that others don't have this issue too. Thanks for letting me know!

**Comment by philnash** [comment]
I've updated the README now, so  I'm going to close this.

Thanks!
