### ISSUE TITLE
How to save friendlyName and Attributes of twilio user?

### ISSUE THREAD

**Issue by santhi-nyros** [philnash/react-programmable-chat#3]
I want to display all channels of a loggedin user.
How can I do this using 'twilio-chat'.
When I using getChannels() and getUserChannelDescriptors() raising " is not a function"
Please help me to fix it.
Thanks

**Comment by philnash** [comment]
Hey, what do you mean when you ask about 'react-twilio'? I'm not using any external libraries in this example application. What are you using?

**Comment by santhi-nyros** [comment]
Hey sorry, it was "twilio-chat". I have fixed it. thanks for reply.

**Comment by santhi-nyros** [comment]
I have another challenge....
how can we save twilio user details like friendlyName, attributes?
when I use this.chatClient.user I get user details but there is null values expect identity, I want store friendlyname and pro_pic...etc.

Please give a some direction to save user details. Thanks

**Comment by philnash** [comment]
Hey @santhi-nyros,

You can store other details against your users using the `attributes` property on a [`User`](https://media.twiliocdn.com/sdk/js/chat/releases/1.2.1/docs/User.html) object. When you first initiate a Client with an access token and identity, the user object won't have fully loaded so you want to listen to the [`updated` event](https://media.twiliocdn.com/sdk/js/chat/releases/1.2.1/docs/User.html#event:updated) that should fire when the user is loaded.

Let me know how you go with that.

**Comment by philnash** [comment]
I left this comment a couple of weeks ago. I'm going to assume that you got it sorted. If not, please do open this up again and I can try to help.

**Comment by santhi-nyros** [comment]
Hi @philnash ,

Thank you. I have fixed the issue.  while creating users , I am giving  attribute and friendlyName too.
Here is my code,
```
var client = new Twilio(config.twilio.accountSid, config.twilio.authToken);

	const service = client.chat.services(config.twilio.chatServiceSid);

	service.users.create({

		identity: identity,

		friendlyName: user.username,

		attributes:JSON.stringify({

			pro_pic:user.pro_pic,

			dob:user.dob

		})

	})

	.then(res => {

	  console.log("new user created ",res.friendlyName);

	})

	.catch(error=> {

		// console.log(error);

		service.users(identity).update({

	    	friendlyName: user.username,

	    	attributes:JSON.stringify({

	    		pro_pic:user.pro_pic,

	    		dob:user.dob

	    	})

		}).then(function(response) {

		    console.log("user update ", response.friendlyName);

		}).catch(function(error) {

		    console.log(error);

		});
		
	});
```

**Comment by philnash** [comment]
That's great to hear you got it sorted!
