### ISSUE TITLE
Date separator between messages form diferent dates not showing

### ISSUE THREAD

**Issue by agch-dev** [philnash/react-programmable-chat#5]
Hi, this is more of a question than an issue.

For some reason copying your example there are no date separators for messages. I was wondering if you knew what configuration I should tweak to get that showing? Twilio documentation of the chat is really bad and I can't find anything.

Thanks

**Comment by philnash** [comment]
Well, each message has a date on which it was created, so you could certainly build date separators yourself. This is just an example project and I didn't think about them when I was building this myself, which is why you won't find them here.

I'd be happy to try to work with you to add date separators to this example if it would help?

**Comment by agch-dev** [comment]
I am fine with not having date separators and have full date and time in each message. The problem is that right now it's just showing the time and I don't have control over the function that outputs the message.

**Comment by philnash** [comment]
What do you mean you don't have control over the function that outputs the message? The entire code used to show the messages is in this repo. You can see the message objects that are emitted by the a channel here: http://media.twiliocdn.com/sdk/js/chat/releases/0.11.0/docs/Message.html. There is a `timestamp` property which is the time the message was sent.

If you have a problem with the code, please feel free to share what you have tried and I will do my best to help.

**Comment by agch-dev** [comment]
Updated the version I was using of twilio's chat and it worked. Sorry for the late response.
