### ISSUE TITLE
Can't connect to twilsock

### ISSUE THREAD

**Issue by abeltyr** [philnash/react-programmable-chat#6]
when I try connecting to Twilio-chat to get chatClient I keep getting this error TransportUnavailableError: Can't connect to twilsock at Upstream.send

**Comment by philnash** [comment]
Do you have all your credentials set correctly in `.env`? Have you changed the code at all?

**Comment by abeltyr** [comment]
ya, I have changed the code and ya I have added mine Twilio credentials in the env and am able to generate the token and get from the get the token and store it in the state token but I facing a problem when I create the chat client by 

    this.chatClient = new Chat(this.state.token);

**Comment by philnash** [comment]
OK, are you using your real credentials or test credentials?

If you are using real credentials, what have you changed with the code? Is the token definitely set in the state at the time you try to create the `Chat` object?

**Comment by abeltyr** [comment]
Yes I have checked the token is set at the moment I create the Chat object yes I am using real credentials. I have taken the express part out and added it to my separate express server and am requesting it through an axios request like this 
 
     getToken = () => {
        axios({
        method:'Post',
         url: `http://localhost:9500/api/token/${this.state.name}`
       }) 
       .then(response => {
           this.setState({ token: response.data.token }, this.initChat);
        })
        .catch(error => {
            console.log(error)
         })
      };
I have checked the token in jwt.io is the same format as the doc says

**Comment by philnash** [comment]
Oh, the Chat SDK has updated since I built this example. I'll have to update it, but now we recommend using the factory function `Chat.create(token)` which returns a promise. Perhaps you could try that instead.

Check out the setup code in this example (that has a different UI): https://github.com/philnash/twilio-chat-kendo-react

**Comment by abeltyr** [comment]
Thank you For the support. I fixed the issue with the help of Twilio support team. For anyone facing this problem, it is a network/firewall issues between the device and Twilio. To test it open the following site and it will check for any issue on your device  

     https://networktest.twilio.com/

**Comment by samsonroy** [comment]
Hi @philnash 

I am using the test credentials and i am facing the same issue.

It says Error: Can't connect to twilsock.

Could you please help me resolving this issue.

**Comment by philnash** [comment]
@samsonroy You can't use test credentials with [Twilio Programmable Chat](https://www.twilio.com/chat). [Test credentials are for making requests to send SMS, make phone calls or buy phone numbers without properly completing the task](https://www.twilio.com/docs/iam/test-credentials).

To use Chat you will need to use your real Account SID.

**Comment by jjercx** [comment]
is this error happening if you try to create a chat client with an expired token?

**Comment by philnash** [comment]
> is this error happening if you try to create a chat client with an expired token?

If you try to create a chat client with an expired token, `Client.create` should reject and you won’t connect.

**Comment by jjercx** [comment]
Interesting. Right now, on login I get a Twilio token and store it. After that, every time my app starts and it's already logged I just used the Twilio token to create the client, and it was working.

After a while, though, I started experiencing the `Can't connect to twilsock` error. I thought it was related to an expired token (haven't implemented token refresh yet), so I just changed the logic to: every time my app starts and it's already logged fetch a new twilio token and then create the client.

@philnash What can be other source for the `Can't connect to twilsock` error? That the app missed internet connection for a moment or something like that?

**Comment by philnash** [comment]
I would definitely recommend creating a new token every time your user wants to connect. 

twilsock is your name for the web socket connection between your browser and Twilio. Anything that could affect a web socket connection, like a lack of internet connection, could cause these errors. If you get them, you can try to catch them then try to reconnect your client.

**Comment by pkonda2019** [comment]
> @samsonroy You can't use test credentials with [Twilio Programmable Chat](https://www.twilio.com/chat). [Test credentials are for making requests to send SMS, make phone calls or buy phone numbers without properly completing the task](https://www.twilio.com/docs/iam/test-credentials).
> 
> To use Chat you will need to use your real Account SID.

@philnash What is "real Account SID" mean in your case, Is it Purchased account or It can be Trial account.

**Comment by philnash** [comment]
@pkonda2019 There are two kinds of account credentials (SID and auth token), test credentials and live credentials. If you go to your [account settings in the Twilio console](https://www.twilio.com/console/project/settings) you will see both. _Do not_ use the TEST credentials for Twilio Chat.

You can use Twilio Chat with a trial account.

**Comment by pkonda2019** [comment]
Hey @philnash thanks for the reply, I verified the same on Twilio console and I am using Live Credentials from console. 
I am using this example [twilio-chat-kendo-react](https://github.com/philnash/twilio-chat-kendo-react) and updated .env with live credentials. And also getting token from server with those same credentials. Even though I am still getting this error

**Error: Can't connect to twilsock**
Can you please helm me into this to successfully execute this example.

**Comment by philnash** [comment]
@pkonda2019 The two reasons that I know of that can cause a failure to connect to twilsock are:

1. A network connection issue
2. An issue with the access token you are generating

I can't do much to troubleshoot the first one. For access tokens, what happens if you enter your access token in the validator at https://jwt.io ? If you enter the API Secret, does it display as verified? Are all the details in the Access Token correct; the Account SID, the API key, the chat service SID?

**Comment by pkonda2019** [comment]
Thanks @philnash 
I verified don't have network issue. Will check for Access token generation.

**Comment by philnash** [comment]
One other question. Is it possible you're testing this on a restrictive network/firewall that isn't allowing outbound websocket connections?

**Comment by htet-lin19** [comment]
Please Some body help me, I'm facing this issue. #####

```
Error: Unable to connect: Unparsable body: '{"identity":"Hello","confirmed_grants":null,"unsafe_grants":null,"auth_account":{"sid":"AC10117c8c64a653e6506b5e77281efae7","parent_account_sid":null,"live_account_sid":null,"status":2,"concurrency_limit":100,"client_cps":5,"flags":[640,2,260,7,2057,11,2060,272,149,405,2069,408,792,538,540,3101,3103,294,680,9001,42,939,559,177,2097,51,692,182,1337,443,447,64,1216,66,35396,453,326,710,35398,201,457,77,79,2001,2002,3539,2004,6997,6998,343,2007,6999,729,2010,2012,2016,2018,484,2020,870,2022,617,1001,2025,618,1002,3310,2032,370,499,9461,8054,9462,9463,888,1016,170104,507,11003,380,253,509,2046],"id":155641762},"registered_claims":{"audience":[],"expiration_time":"2022-06-15T04:24:04Z","issued_at":null,"issuer":"SK65fa4304d1f6444222ebd02fd3aab996","jwt_id":"SK65fa4304d1f6444222ebd02fd3aab996-1655263444","not_before":null,"subject":"AC10117c8c64a653e6506b5e77281efae7"},"account_properties":{"twilsock":{}}}'
    at Upstream.send (upstream.js:150:1)
    at TwilsockClient.post (client.js:196:1)
    at network.js:122:1
    at Retrier.<anonymous> (network.js:80:1)
    at Retrier.emit (events.js:153:1)
    at Retrier.attempt (retrier.ts:58:1)
    at retrier.ts:113:1
console.<computed> @ index.js:1
```

**Comment by philnash** [comment]
Hi @htet-lin19, what is this a log of? It looks like an incorrectly configured access token is part of this log, what is going on with that?

Can you share your code at all?

**Comment by htet-lin19** [comment]
Hai, I use laravel and react , get token from laravel api. 

**Laravel API**

```php
<?php

namespace App\Http\Controllers\api\v1;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Twilio\Jwt\AccessToken;
use Twilio\Jwt\Grants\VideoGrant;
use Twilio\Jwt\Grants\ChatGrant;
use Twilio\Jwt\Grants\SyncGrant;
use Illuminate\Support\Facades\Validator;

class RoomController extends Controller
{
    private $sid, $apiKey, $apiSecret;
    private $chat, $notify, $sync;

    public function __construct()
    {
        $this->sid = config('services.twilio.sid');
        $this->apiKey = config('services.twilio.api_key');
        $this->apiSecret = config('services.twilio.api_secret');

        $this->chat = config('twilio_chat.chat_service');
        $this->notify = config('twilio_chat.notify_service');
        $this->sync = config('twilio_chat.sync_service');
    }

    function tokenGenerator(Request $request)
    {
        $identity = $request->identity;
        // $identity = "Willan Finish";

        $token = new AccessToken(
            $this->sid,
            $this->apiKey,
            $this->apiSecret,
            3600,
            $identity
        );

        if ($this->chat) {
            $chatGrant = new ChatGrant();
            $chatGrant->setServiceSid($this->chat);
            $token->addGrant($chatGrant);
        }
        return ['token'=>$token->toJWT()];
    }

}

```

front end
```js
import React, { Component } from 'react';
import Chat from 'twilio-chat';
import { Chat as ChatUI } from '@progress/kendo-react-conversational-ui';

class ChatApp extends Component {
  constructor(props) {
    super(props);
    this.state = {
      error: null,
      isLoading: true,
      messages: []
    };

    this.user = {
      id: props.username,
      name: props.username
    };

    this.setupChatClient = this.setupChatClient.bind(this);
    this.messagesLoaded = this.messagesLoaded.bind(this);
    this.messageAdded = this.messageAdded.bind(this);
    this.sendMessage = this.sendMessage.bind(this);
    this.handleError = this.handleError.bind(this);

  }

  componentDidMount() {
    fetch('http://127.0.0.1:8000/api/v1/getChatToken', {
      headers: { 
      'Content-Type': 'application/x-www-form-urlencoded'
    },
      method: 'POST',
      body: `identity=${encodeURIComponent(this.props.username)}`,
    })
      .then(res => res.json())
      .then(data => Chat.create(data.token))
      .then(this.setupChatClient)
      .catch(this.handleError);
  }

  handleError(error) {
    console.error(error);
    this.setState({
      error: 'Could not load chat.'
    });
  }

  setupChatClient(client) {
    this.client = client;
    this.client
      .getChannelByUniqueName('general2')
      .then(channel => channel)
      .catch(error => {
        if (error.body.code === 50300) {
          return this.client.createChannel({ uniqueName: 'general2' });
        } else {
          this.handleError(error);
        }
      })
      .then(channel => {
        this.channel = channel;
        return this.channel.join().catch(() => {});
      })
      .then(() => {
        this.setState({ isLoading: false });
        this.channel.getMessages().then(this.messagesLoaded);
        this.channel.on('messageAdded', this.messageAdded);
      })
      .catch(this.handleError);
  }

  twilioMessageToKendoMessage(message) {
    return {
      text: message.body,
      author: { id: message.author, name: message.author },
      timestamp: message.timestamp
    };
  }

  messagesLoaded(messagePage) {
    this.setState({
      messages: messagePage.items.map(this.twilioMessageToKendoMessage)
    });
  }

  messageAdded(message) {
    this.setState(prevState => ({
      messages: [
        ...prevState.messages,
        this.twilioMessageToKendoMessage(message)
      ]
    }));
  }

  sendMessage(event) {
    this.channel.sendMessage(event.message.text);
  }

  componentWillUnmount() {
    this.client.shutdown();
  }

  render() {
    if (this.state.error) {
      return <p>{this.state.error}</p>;
    } else if (this.state.isLoading) {
      return <p>Loading chat...</p>;
    }
    return (
      <ChatUI
        user={this.user}
        messages={this.state.messages}
        onMessageSend={this.sendMessage}
        width={500}
      />
    );
  }
}

export default ChatApp;
```

**Comment by philnash** [comment]
Ok, I recommend that you stop working with the Twilio Chat API as [it is being sunset on 25th July 2022](https://www.twilio.com/changelog/programmable-chat-end-of-life). If you haven't already launched, then I recommend you switch or [migrate to the Conversations API](https://www.twilio.com/docs/conversations/migrating-chat-conversations).

I think that there is only a month left of this product, that is a bigger issue than your error here.
