### ISSUE TITLE
Async hooks issue in client app 

### ISSUE THREAD

**Issue by Az1m04** [philnash/react-programmable-chat#8]
Hello philnash,

![image](https://user-images.githubusercontent.com/42888008/187900661-4ac4a738-e426-479e-bf40-0b0ccc257ba2.png)

while runing the app i am getting this.

**Comment by philnash** [comment]
Hey @Az1m04, I'm afraid I don't think this error is worth fixing. The last commit to this project was almost 5 years ago, it uses React version 15, and, most importantly, [Twilio Chat was sunset last month](https://www.twilio.com/changelog/programmable-chat-end-of-life).

I recommend you take a look at the [Twilio Conversations Quick Start](https://www.twilio.com/docs/conversations/quickstart) to see the latest in what we are working on regarding live chat SDKs, as well as an up to date example.

I'm going to archive this project. Thanks for checking it out though.
